# Generated by Django 3.2.13 on 2022-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('topic', models.CharField(max_length=10000)),
                ('subtopic', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
