# Generated by Django 3.2.13 on 2022-09-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='blog_post',
            name='pick',
            field=models.ManyToManyField(related_name='pick', to='base.category'),
        ),
    ]
